### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by mehdi-cit** [LiikeJS/Liike#9]
Hello and thank you for sharing Liike with the rest of us.
Would you mind adding in the read me file information about what browsers Liike does support.
Thanks 👍

**Comment by pakastin** [comment]
Good point! The only thing that requires a ”newer” browser is `requestAnimationFrame` which has been around since IE10. You can polyfill it pretty easily though.

I’ll add this information to the readme. Thanks! 😎👍

**Comment by pakastin** [comment]
Added!
